UPDATE app_user
SET
  username = $2,
  first_name = $3,
  middle_name = $4,
  last_name = $5,
  street_address = $6,
  suite_number = $7,
  city = $8,
  state_us = $9,
  zip_code = $10,
  phone_number = $11,
  ss_number = $12,
  birth_date = $13,
  starting_date = $14,
  terminated_date = $15,
  is_active = $16,
  role_id = $17,
  updated_at = now()
WHERE id = $1
RETURNING
  id,
  username,
  password_hash,
  first_name,
  middle_name,
  last_name,
  street_address,
  suite_number,
  city,
  state_us,
  zip_code,
  phone_number,
  ss_number,
  birth_date,
  starting_date,
  terminated_date,
  is_active,
  role_id,
  created_at,
  updated_at;
