import { Pool, PoolClient } from 'pg';
import { loadSql } from '../../db/sqlLoader';
import { PawnTicketRepository } from '../../../domains/pawnTicket/PawnTicketRepository';
import { PawnTicket } from '../../../domains/pawnTicket/PawnTicket';


type DbClient = Pool | PoolClient;

const SQL_CREATE = loadSql(
    'commands',
    'pawnTicket/pawn_ticket_create'
);

const SQL_LIST_BY_CONTROL_NUMBER = loadSql(
    'queries',
    'pawnTicket/pawn_ticket_list_by_control_number'
);

const SQL_FIND_BY_CUSTOMER = loadSql(
    'queries',
    'pawnTicket/pawn_ticket_find_by_customer'
);

const SQL_LIST_ACTIVE_BY_CUSTOMER = loadSql(
    'queries',
    'pawnTicket/pawn_ticket_list_active_by_customer'
);

function mapRowToPawnTicket(row: any): PawnTicket {
    return new PawnTicket({
        id: row.id,
        controlNumber: row.control_number,
        transactionType: row.transaction_type,
        customerId: row.customer_id,
        amountFinanced:
            row.amount_financed !== null ? Number(row.amount_financed) : null,
        purchaseTradeValue:
            row.purchase_trade_value !== null
                ? Number(row.purchase_trade_value)
                : null,
        transactionDate: row.transaction_date,
        maturityDate: row.maturity_date,
        defaultDate: row.default_date,
        pawnStatus: row.pawn_status,
        itemIds: Array.isArray(row.item_ids) ? row.item_ids : []
    });
}

export class PgPawnTicketRepository implements PawnTicketRepository {
    constructor(private readonly db: DbClient) { }

    async create(ticket: PawnTicket): Promise<PawnTicket> {
        const result = await this.db.query(SQL_CREATE, [
            ticket.id,
            ticket.transactionType,
            ticket.customerId,
            ticket.amountFinanced,
            ticket.purchaseTradeValue,
            ticket.transactionDate,
            ticket.maturityDate,
            ticket.defaultDate,
            ticket.itemIds
        ]);

        const row = result.rows[0];

        // Use the control_number generated by the DB, but we already know itemIds
        const created = mapRowToPawnTicket({
            ...row,
            item_ids: ticket.itemIds
        });

        return created;
    }

    async listByControlNumber(controlNumber: string): Promise<PawnTicket[]> {
        const result = await this.db.query(SQL_LIST_BY_CONTROL_NUMBER, [
            controlNumber
        ]);
        return result.rows.map(mapRowToPawnTicket);
    }

    async findByCustomer(customerId: string): Promise<PawnTicket[]> {
        const result = await this.db.query(SQL_FIND_BY_CUSTOMER, [customerId]);
        return result.rows.map(mapRowToPawnTicket);
    }

    async listActiveByCustomer(customerId: string): Promise<PawnTicket[]> {
        const result = await this.db.query(SQL_LIST_ACTIVE_BY_CUSTOMER, [
            customerId
        ]);
        return result.rows.map(mapRowToPawnTicket);
    }
}
